global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: [ 'alertname' ]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alert'
        send_resolved: true
